# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240a7a80de534eba54a42452642933386d6041d0853f2bb6b93323ccbe264b7fa0f639e0706b7305245c8b3448554ef48c7d0fc2c3bad55fe585fd4d26256b7a

test:
  secret_key_base: 0aad87536126af428c341336aac3692d86741baa18933a31bff20bdb9916cfb808d96d78fac2cfc680ab7a88ce397e611fce69ee55719443629d9786ab8ae6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
